services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: dkd-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 128m
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN: "ZGtkLW5hY29zLWRldi10b2tlbi1zZWNyZXQta2V5LTIwMjYtY2hhbmdlLW1l"
      NACOS_AUTH_IDENTITY_KEY: "dkdNacosServer"
      NACOS_AUTH_IDENTITY_VALUE: "dkdNacosServerSecret"
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./docker/nacos/logs:/home/nacos/logs
      - ./docker/nacos/data:/home/nacos/data
    restart: unless-stopped
